### ISSUE TITLE
Missing NAND/SD manufacture Swissbit (0x5d) in storage information section 

### ISSUE THREAD

**Issue by WiiNewU** [GaryOderNichts/WiiUIdent#12]
Hello, in the storage information section, it is missing my brand of SD Card (Swissbit). I did check online and the (0x5d) manufacture ID does point to Swissbit correctly (so it's not a counterfeit). Thank you.
![2024-08-Swissbit-Storage-Unknown](https://github.com/user-attachments/assets/77cad3ce-fd26-46e6-a4eb-0e58369c9263)

**Comment by GaryOderNichts** [comment]
Thanks!
